"""
Train a baseline linear regression model to predict next-interval flow.

Inputs:
- data/flows_train.csv, data/flows_val.csv (generated by generate_synthetic_flows.py)

Outputs:
- models/linear_flow.pkl : trained scikit-learn LinearRegression
- data/forecast_example.json : sample forecast for the first val timestamp per edge
- data/metrics_linear.json : simple metrics (RMSE on val)
"""

import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

DATA_DIR = Path("data")
MODELS_DIR = Path("models")

FEATURES = [
    "hour",
    "day_of_week",
    "is_peak",
    "capacity",
    "length_m",
    "flow_lag1",
    "flow_lag2",
]
TARGET = "flow"


def load_splits():
    train_df = pd.read_csv(DATA_DIR / "flows_train.csv")
    val_df = pd.read_csv(DATA_DIR / "flows_val.csv")
    return train_df, val_df


def prepare_xy(df: pd.DataFrame):
    X = df[FEATURES].copy()
    y = df[TARGET].copy()
    # fill missing lags with small value
    X = X.fillna(0.0)
    return X, y


def main():
    train_df, val_df = load_splits()
    X_train, y_train = prepare_xy(train_df)
    X_val, y_val = prepare_xy(val_df)

    model = LinearRegression()
    model.fit(X_train, y_train)

    val_pred = model.predict(X_val)
    rmse = float(np.sqrt(mean_squared_error(y_val, val_pred)))

    MODELS_DIR.mkdir(exist_ok=True)
    joblib.dump(model, MODELS_DIR / "linear_flow.pkl")

    metrics = {"rmse_val": rmse}
    (DATA_DIR / "metrics_linear.json").write_text(json.dumps(metrics, indent=2))

    # Produce a simple forecast snapshot for the first val timestamp per edge
    snapshot = []
    first_t = val_df["t"].min()
    snap_df = val_df[val_df["t"] == first_t].copy()
    snap_X, _ = prepare_xy(snap_df)
    snap_df["pred_flow"] = model.predict(snap_X)
    for _, row in snap_df.iterrows():
        snapshot.append(
            {
                "edge_id": row["edge_id"],
                "t": int(row["t"]),
                "pred_flow": float(row["pred_flow"]),
                "capacity": float(row["capacity"]),
            }
        )
    (DATA_DIR / "forecast_example.json").write_text(json.dumps(snapshot, indent=2))

    print(f"Trained linear model. Val RMSE={rmse:.2f}, forecast entries={len(snapshot)}")


if __name__ == "__main__":
    main()
